//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationHR.Models.DM
{
    using System;
    using System.Collections.Generic;
    
    public partial class HR
    {
        public int Id { get; set; }
        public string FName { get; set; }
        public string MName { get; set; }
        public string LName { get; set; }
        public string Gender { get; set; }
        public string c_residence { get; set; }
        public string address { get; set; }
        public string m_number { get; set; }
        public string email { get; set; }
        public string d_work { get; set; }
        public string r_status { get; set; }
        public string m_status { get; set; }
        public Nullable<int> n_kids { get; set; }
        public string s_date { get; set; }
        public string branch { get; set; }
        public string title { get; set; }
        public string salary { get; set; }
        public string off_day { get; set; }
        public string u_name { get; set; }
        public string u_address { get; set; }
        public string u_years { get; set; }
        public string u_grad { get; set; }
        public string degree { get; set; }
        public string v_name { get; set; }
        public string v_years { get; set; }
        public string v_training { get; set; }
        public string sa_name { get; set; }
        public string sa_address { get; set; }
        public string sa_years { get; set; }
        public string so_name { get; set; }
        public string so_address { get; set; }
        public string so_years { get; set; }
        public string p_name { get; set; }
        public string p_address { get; set; }
        public string nid_number { get; set; }
        public string nssf { get; set; }
        public string dr_li { get; set; }
        public string dr_li_exp { get; set; }
        public string pre_job { get; set; }
        public string position { get; set; }
        public string time { get; set; }
        public string emp_name { get; set; }
        public string emp_address { get; set; }
        public string supervisor { get; set; }
        public string last_day { get; set; }
        public string emer_name { get; set; }
        public string emer_number { get; set; }
        public string image { get; set; }
    }
}
